from django.db import migrations, models
import django.db.models.deletion


def seed_defaults(apps, schema_editor):
    TeamPosition=apps.get_model('teams','TeamPosition')
    Portfolio=apps.get_model('teams','Portfolio')
    for i,(name,cat) in enumerate([('Chairman','Leadership'),('Honorary Secretary','Leadership'),('Member','Board'),('Portfolio Lead','Portfolio'),('Helper','Portfolio')],1):
        TeamPosition.objects.get_or_create(name=name,defaults={'category':cat,'sort_order':i*10})
    for i,name in enumerate(['Family Harmony','Seniors','Health','Education','Economic Planning','Special Needs'],1):
        Portfolio.objects.get_or_create(name=name,defaults={'code':name.upper().replace(' ','_'),'sort_order':i*10})

class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length'),('boards','0001_initial'),('organization','0004_seed_central_region_local_councils'),('people','0002_person_cnic_images')]
    operations=[
        migrations.CreateModel(name='Portfolio',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('code',models.CharField(max_length=50,unique=True)),('sort_order',models.PositiveIntegerField(default=0)),('is_active',models.BooleanField(default=True))],options={'ordering':['sort_order','name']}),
        migrations.CreateModel(name='TeamPosition',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100,unique=True)),('category',models.CharField(blank=True,max_length=80)),('sort_order',models.PositiveIntegerField(default=0)),('is_active',models.BooleanField(default=True))],options={'ordering':['sort_order','name']}),
        migrations.CreateModel(name='Term',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80,unique=True)),('start_date',models.DateField()),('end_date',models.DateField()),('is_current',models.BooleanField(default=False)),('is_active',models.BooleanField(default=True)),('notes',models.TextField(blank=True)),('sort_order',models.PositiveIntegerField(default=0))],options={'ordering':['-is_current','-start_date','sort_order','name']}),
        migrations.CreateModel(name='TeamAppointment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('level',models.CharField(choices=[('NATIONAL','National'),('REGIONAL','Regional'),('LOCAL','Local Council'),('JK','Jamatkhana')],max_length=12)),('appointment_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('is_active',models.BooleanField(default=True)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('board',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='team_appointments',to='boards.board')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='team_appointments_created',to='auth.user')),('jamatkhana',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='team_appointments',to='organization.jamatkhana')),('local_council',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='team_appointments',to='organization.localcouncil')),('national_council',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='team_appointments',to='organization.nationalcouncil')),('person',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='team_appointments',to='people.person')),('portfolio',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='appointments',to='teams.portfolio')),('position',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='appointments',to='teams.teamposition')),('regional_council',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='team_appointments',to='organization.regionalcouncil')),('term',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='appointments',to='teams.term')),('covered_jamatkhanas',models.ManyToManyField(blank=True,related_name='covered_team_appointments',to='organization.jamatkhana'))],options={'ordering':['term','board','level','position__sort_order','person__full_name']}),
        migrations.AddIndex(model_name='teamappointment',index=models.Index(fields=['term','board','level','is_active'],name='teams_teama_term_id_60b9a0_idx')),
        migrations.AddIndex(model_name='teamappointment',index=models.Index(fields=['regional_council','local_council','jamatkhana'],name='teams_teama_regiona_3b59e7_idx')),
        migrations.RunPython(seed_defaults,migrations.RunPython.noop),
    ]
