# Generated by Django 5.2.6 on 2026-10-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_categories_board_portfolios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['board__sort_order', 'board__name', 'sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='teamappointment',
            options={'ordering': ['position__sort_order', 'position__name', 'person__full_name']},
        ),
        migrations.RenameIndex(
            model_name='teamappointment',
            new_name='teams_teama_term_id_2d35de_idx',
            old_name='teams_teama_term_id_60b9a0_idx',
        ),
        migrations.RenameIndex(
            model_name='teamappointment',
            new_name='teams_teama_regiona_216593_idx',
            old_name='teams_teama_regiona_3b59e7_idx',
        ),
    ]
