# Generated by Django 5.2.6 on 2026-09-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jamatkhana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('local_council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jamatkhanas', to='organization.localcouncil')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('national_council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='organization.nationalcouncil')),
            ],
        ),
        migrations.AddField(
            model_name='localcouncil',
            name='regional_council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locals', to='organization.regionalcouncil'),
        ),
        migrations.CreateModel(
            name='UserJurisdictionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('LOCAL', 'Local'), ('JK', 'Jamatkhana')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_jurisdictions', to=settings.AUTH_USER_MODEL)),
                ('jamatkhana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.jamatkhana')),
                ('local_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.localcouncil')),
                ('national_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.nationalcouncil')),
                ('regional_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.regionalcouncil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='jamatkhana',
            index=models.Index(fields=['local_council', 'is_active'], name='organizatio_local_c_6538eb_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalcouncil',
            index=models.Index(fields=['national_council', 'is_active'], name='organizatio_nationa_17cd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='localcouncil',
            index=models.Index(fields=['regional_council', 'is_active'], name='organizatio_regiona_12879e_idx'),
        ),
        migrations.AddIndex(
            model_name='userjurisdictionaccess',
            index=models.Index(fields=['user', 'level', 'is_active'], name='organizatio_user_id_39ec33_idx'),
        ),
    ]
