# Generated by Django 5.2.6 on 2026-09-20 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_admin_defaults(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    admin_user = User.objects.filter(username='admin').first()
    if admin_user:
        admin_user.is_superuser = True
        admin_user.is_staff = True
        admin_user.is_active = True
        admin_user.save(update_fields=['is_superuser', 'is_staff', 'is_active'])
        UserProfile.objects.update_or_create(user_id=admin_user.pk, defaults={'phone_number': '03122550183'})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(set_admin_defaults, migrations.RunPython.noop),
    ]
