# Generated by Django 5.2.6 on 2026-09-20 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHarmonyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_CONSENT', 'Awaiting consent'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('INTRODUCTION_PENDING', 'Introduction pending'), ('IN_DISCUSSION', 'In discussion'), ('FAMILY_MEETING', 'Family meeting'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=180)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('profession', models.CharField(blank=True, max_length=180)),
                ('years_experience', models.CharField(blank=True, max_length=80)),
                ('financial_status', models.CharField(blank=True, max_length=120)),
                ('family_background', models.TextField(blank=True)),
                ('place_of_origin', models.CharField(blank=True, max_length=160)),
                ('family_values', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('smoking', models.CharField(blank=True, max_length=60)),
                ('other_lifestyle_details', models.TextField(blank=True)),
                ('children_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child_details', models.TextField(blank=True)),
                ('previous_marriage_notes', models.TextField(blank=True)),
                ('disabilities', models.TextField(blank=True)),
                ('health_information', models.TextField(blank=True)),
                ('personal_statement', models.TextField(blank=True)),
                ('expectations', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('consent_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owning_jamatkhana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.jamatkhana')),
                ('owning_local_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.localcouncil')),
                ('owning_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.regionalcouncil')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='harmony_profile', to='people.person')),
            ],
            options={
                'permissions': [('share_profile', 'Can share profile'), ('release_contact', 'Can release contact'), ('approve_cross_region', 'Can approve cross-jurisdiction introductions')],
            },
        ),
        migrations.CreateModel(
            name='FamilyHarmonyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('preferred_regions', models.JSONField(blank=True, default=list)),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('preferred_education', models.CharField(blank=True, max_length=180)),
                ('preferred_professions', models.JSONField(blank=True, default=list)),
                ('preferred_income', models.CharField(blank=True, max_length=120)),
                ('preferred_marital_status', models.CharField(blank=True, max_length=120)),
                ('preferred_family_values', models.TextField(blank=True)),
                ('preferred_personality', models.TextField(blank=True)),
                ('willingness_to_relocate', models.BooleanField(default=False)),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('other_expectations', models.TextField(blank=True)),
                ('free_text_seeking_description', models.TextField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='family_harmony.familyharmonyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(max_length=80)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(blank=True, max_length=80)),
                ('profile_sharing_allowed', models.BooleanField(default=False)),
                ('photo_sharing_allowed', models.BooleanField(default=False)),
                ('contact_release_allowed', models.BooleanField(default=False)),
                ('health_data_sharing_allowed', models.BooleanField(default=False)),
                ('disability_data_sharing_allowed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('obtained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='people.person')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_revoked', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='family_harmony.familyharmonyprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='familyharmonyprofile',
            index=models.Index(fields=['status'], name='family_harm_status_d6147e_idx'),
        ),
        migrations.AddIndex(
            model_name='familyharmonyprofile',
            index=models.Index(fields=['owning_region', 'owning_local_council', 'owning_jamatkhana'], name='family_harm_owning__e5f47a_idx'),
        ),
        migrations.AddIndex(
            model_name='familyharmonyprofile',
            index=models.Index(fields=['assigned_officer', 'status'], name='family_harm_assigne_24e92d_idx'),
        ),
    ]
