# Generated by Django 5.2.6 on 2026-09-20 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_harmony', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossJurisdictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More information requested')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requester_jk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_from', to='organization.jamatkhana')),
                ('requester_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_from', to='organization.localcouncil')),
                ('requester_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_from', to='organization.regionalcouncil')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_source', to='family_harmony.familyharmonyprofile')),
                ('target_jk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_to', to='organization.jamatkhana')),
                ('target_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_to', to='organization.localcouncil')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_target', to='family_harmony.familyharmonyprofile')),
                ('target_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_requests_to', to='organization.regionalcouncil')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MUTUAL_INTEREST', 'Mutual interest'), ('IN_DISCUSSION', 'In discussion'), ('FAMILY_MEETING', 'Family meeting'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('CLOSED', 'Closed')], default='PENDING', max_length=30)),
                ('contact_released_at', models.DateTimeField(blank=True, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_releases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='introductions_started', to='family_harmony.familyharmonyprofile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='introductions_received', to='family_harmony.familyharmonyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PublicFormInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('candidate_name', models.CharField(blank=True, max_length=180)),
                ('candidate_phone', models.CharField(blank=True, max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('preselected_jamatkhana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.jamatkhana')),
                ('preselected_local_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.localcouncil')),
                ('preselected_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.regionalcouncil')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_invitations', to='family_harmony.familyharmonyprofile')),
            ],
        ),
    ]
