# Generated by Django 5.2.6 on 2026-09-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_harmony', '0002_crossjurisdictionrequest_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='income_range',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
