# Generated by Django 5.2.6 on 2026-09-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_harmony', '0003_familyharmonyprofile_income_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='employer_or_business',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
