# Generated by Django 5.2.6 on 2026-09-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_harmony', '0004_familyharmonyprofile_employer_or_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyharmonyprofile',
            name='portfolio',
            field=models.CharField(blank=True, default='Family Harmony', max_length=100),
        ),
    ]
