# Generated by Django 5.2.6 on 2026-09-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=305)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='Pakistani', max_length=80)),
                ('identity_type', models.CharField(blank=True, choices=[('CNIC', 'CNIC'), ('NICOP', 'NICOP'), ('BFORM_CRC', 'B-Form / CRC'), ('PASSPORT', 'Passport'), ('BIRTH_CERTIFICATE', 'Birth certificate'), ('OTHER', 'Other')], max_length=30)),
                ('identity_number', models.CharField(blank=True, max_length=80)),
                ('normalized_identity_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('alternate_mobile', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=160)),
                ('education_details', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=160)),
                ('employer_or_business', models.CharField(blank=True, max_length=160)),
                ('income_range', models.CharField(blank=True, max_length=80)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('interests', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='people/%Y/%m/')),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('other_social_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_created', to=settings.AUTH_USER_MODEL)),
                ('jamatkhana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='organization.jamatkhana')),
                ('local_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='organization.localcouncil')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='organization.regionalcouncil')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_full_cnic', 'Can view full CNIC'), ('export_person', 'Can export person data')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=60)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='people.family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('guardian', 'Guardian'), ('dependent', 'Dependent'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='people.person')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='people.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name'], name='people_pers_full_na_9fcb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['mobile'], name='people_pers_mobile_9afed1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='people_pers_date_of_c1209b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['region', 'local_council', 'jamatkhana'], name='people_pers_region__a86198_idx'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('family', 'person'), name='unique_family_member'),
        ),
        migrations.AddConstraint(
            model_name='personrelationship',
            constraint=models.UniqueConstraint(fields=('person', 'related_person', 'relationship_type'), name='unique_person_relationship'),
        ),
    ]
