# Generated by Django 5.2.6 on 2026-09-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHarmonySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_expiry_days', models.PositiveSmallIntegerField(default=4)),
                ('minimum_expiry_days', models.PositiveSmallIntegerField(default=1)),
                ('maximum_expiry_days', models.PositiveSmallIntegerField(default=30)),
                ('default_max_views', models.PositiveIntegerField(default=5)),
                ('require_last_four_cnic', models.BooleanField(default=False)),
                ('photo_visibility', models.CharField(default='after_interest', max_length=30)),
                ('name_visibility', models.CharField(default='full_name', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Harmony settings',
            },
        ),
    ]
