# Generated by Django 5.2.6 on 2026-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyharmonysettings',
            name='education_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='familyharmonysettings',
            name='title_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
