# Generated by Django 5.2.6 on 2026-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_familyharmonysettings_education_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyharmonysettings',
            name='employer_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='familyharmonysettings',
            name='income_ranges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='familyharmonysettings',
            name='occupation_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
