# Generated by Django 5.2.6 on 2026-09-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_familyharmonysettings_employer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyharmonysettings',
            name='portfolio_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
